server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: 'http://loki:3100/loki/api/v1/push'
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: 'unix:///var/run/docker.sock'
        refresh_interval: 5s
    # Секция с склеиванием лога и чистка от маркеров
    pipeline_stages:
      - json:
          expressions:
            message: log
      - output:
          source: message
      - multiline:
          firstline: '(startlogline)'
          max_lines: 600 # важный параметр, если уменьшить то будет рвать склеенный лог
          max_wait_time: 3s
      - replace:
          expression: '(startlogline)'
          replace: ''
      - replace:
          expression: '(endlogline)'
          replace: ''
    relabel_configs:
      - source_labels:
          - __meta_docker_container_name
        regex: /(.*)
        target_label: container
      - source_labels:
          - __meta_docker_container_log_stream
        target_label: logstream